name: Jest Codecov Reporter

on:
  push:
    branches: [master]

jobs:
  CodeCov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: test and report upload
        run: |
          npm install
          npm run test
          npx codecov -t ${{secrets.CODECOV_KEY}}
